/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthenticatedKnowledgeIndexRouteImport } from './routes/_authenticated/knowledge/index'
import { Route as AuthenticatedLessonsIndexRouteImport } from './routes/_authenticated/lessons/index'
import { Route as AuthenticatedOverviewIndexRouteImport } from './routes/_authenticated/overview/index'
import { Route as AuthenticatedSearchIndexRouteImport } from './routes/_authenticated/search/index'
import { Route as AuthenticatedSessionsIndexRouteImport } from './routes/_authenticated/sessions/index'
import { Route as PublicLoginIndexRouteImport } from './routes/_public/login/index'
import { Route as AuthenticatedSessionsSessionIdIndexRouteImport } from './routes/_authenticated/sessions/$sessionId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedKnowledgeIndexRoute =
  AuthenticatedKnowledgeIndexRouteImport.update({
    id: '/knowledge/',
    path: '/knowledge/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLessonsIndexRoute =
  AuthenticatedLessonsIndexRouteImport.update({
    id: '/lessons/',
    path: '/lessons/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOverviewIndexRoute =
  AuthenticatedOverviewIndexRouteImport.update({
    id: '/overview/',
    path: '/overview/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSearchIndexRoute =
  AuthenticatedSearchIndexRouteImport.update({
    id: '/search/',
    path: '/search/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessionsIndexRoute =
  AuthenticatedSessionsIndexRouteImport.update({
    id: '/sessions/',
    path: '/sessions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const PublicLoginIndexRoute = PublicLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthenticatedSessionsSessionIdIndexRoute =
  AuthenticatedSessionsSessionIdIndexRouteImport.update({
    id: '/sessions/$sessionId/',
    path: '/sessions/$sessionId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/knowledge/': typeof AuthenticatedKnowledgeIndexRoute
  '/lessons/': typeof AuthenticatedLessonsIndexRoute
  '/overview/': typeof AuthenticatedOverviewIndexRoute
  '/search/': typeof AuthenticatedSearchIndexRoute
  '/sessions/': typeof AuthenticatedSessionsIndexRoute
  '/login/': typeof PublicLoginIndexRoute
  '/sessions/$sessionId/': typeof AuthenticatedSessionsSessionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/knowledge': typeof AuthenticatedKnowledgeIndexRoute
  '/lessons': typeof AuthenticatedLessonsIndexRoute
  '/overview': typeof AuthenticatedOverviewIndexRoute
  '/search': typeof AuthenticatedSearchIndexRoute
  '/sessions': typeof AuthenticatedSessionsIndexRoute
  '/login': typeof PublicLoginIndexRoute
  '/sessions/$sessionId': typeof AuthenticatedSessionsSessionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_authenticated/knowledge/': typeof AuthenticatedKnowledgeIndexRoute
  '/_authenticated/lessons/': typeof AuthenticatedLessonsIndexRoute
  '/_authenticated/overview/': typeof AuthenticatedOverviewIndexRoute
  '/_authenticated/search/': typeof AuthenticatedSearchIndexRoute
  '/_authenticated/sessions/': typeof AuthenticatedSessionsIndexRoute
  '/_public/login/': typeof PublicLoginIndexRoute
  '/_authenticated/sessions/$sessionId/': typeof AuthenticatedSessionsSessionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/knowledge/'
    | '/lessons/'
    | '/overview/'
    | '/search/'
    | '/sessions/'
    | '/login/'
    | '/sessions/$sessionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/knowledge'
    | '/lessons'
    | '/overview'
    | '/search'
    | '/sessions'
    | '/login'
    | '/sessions/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/knowledge/'
    | '/_authenticated/lessons/'
    | '/_authenticated/overview/'
    | '/_authenticated/search/'
    | '/_authenticated/sessions/'
    | '/_public/login/'
    | '/_authenticated/sessions/$sessionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/knowledge/': {
      id: '/_authenticated/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof AuthenticatedKnowledgeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lessons/': {
      id: '/_authenticated/lessons/'
      path: '/lessons'
      fullPath: '/lessons/'
      preLoaderRoute: typeof AuthenticatedLessonsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/overview/': {
      id: '/_authenticated/overview/'
      path: '/overview'
      fullPath: '/overview/'
      preLoaderRoute: typeof AuthenticatedOverviewIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search/': {
      id: '/_authenticated/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof AuthenticatedSearchIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions/': {
      id: '/_authenticated/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof AuthenticatedSessionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_public/login/': {
      id: '/_public/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof PublicLoginIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_authenticated/sessions/$sessionId/': {
      id: '/_authenticated/sessions/$sessionId/'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId/'
      preLoaderRoute: typeof AuthenticatedSessionsSessionIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedKnowledgeIndexRoute: typeof AuthenticatedKnowledgeIndexRoute
  AuthenticatedLessonsIndexRoute: typeof AuthenticatedLessonsIndexRoute
  AuthenticatedOverviewIndexRoute: typeof AuthenticatedOverviewIndexRoute
  AuthenticatedSearchIndexRoute: typeof AuthenticatedSearchIndexRoute
  AuthenticatedSessionsIndexRoute: typeof AuthenticatedSessionsIndexRoute
  AuthenticatedSessionsSessionIdIndexRoute: typeof AuthenticatedSessionsSessionIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedKnowledgeIndexRoute: AuthenticatedKnowledgeIndexRoute,
  AuthenticatedLessonsIndexRoute: AuthenticatedLessonsIndexRoute,
  AuthenticatedOverviewIndexRoute: AuthenticatedOverviewIndexRoute,
  AuthenticatedSearchIndexRoute: AuthenticatedSearchIndexRoute,
  AuthenticatedSessionsIndexRoute: AuthenticatedSessionsIndexRoute,
  AuthenticatedSessionsSessionIdIndexRoute:
    AuthenticatedSessionsSessionIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PublicRouteRouteChildren {
  PublicLoginIndexRoute: typeof PublicLoginIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicLoginIndexRoute: PublicLoginIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
